### PR TITLE
[v1.29] Add k8s v1.29 support 

### PR DESCRIPTION
**Pull request by krunalhinguu**
### Related

- https://github.com/rancher/rancher/issues/43110

### Update

- Add v1.29 support till March patches(1.29.3).

### TODO

- [x]  A new base branch needs to be created in rancher/client-go repo for release-1.29 using the upstream client go 0.29.3 tag, and then the base branch of this PR needs to be updated with the created branch.

### CODE REVIEW

**Comment by kinarashah** [comment]
@krunalhinguu Could you rebase? That way the list would show only 2 rancher specific commits.

**Comment by kinarashah** [comment]
Looks like fix for [d286376](https://github.com/rancher/client-go/pull/11/commits/d28637643de6ed589b6bb154143a312c4e4eff6b) is going to be merged in v1.30 so we can evaluate if we can get rid of [c06ed20](https://github.com/rancher/client-go/pull/11/commits/c06ed20faf87ba276798655d9ec17cda9f61ee64) too and then use upstream tag directly.

**Comment by krunalhinguu** [comment]
@kinarashah i think rebase will sync release-1.29 branch data into my branch, we have tried that and it was not working

**Comment by krunalhinguu** [comment]
like release-1.29 branch already has cherry-pick changes, so if i do rebase cherry-picked changes in my current branch will become null and void.

So i had to merge with the upstream `release-v1.29` branch as there were merge conflicts while adding 0.29.3 on top of it.

https://github.com/rancher/client-go/commits/release-1.29/

**Review by kinarashah — APPROVED** [review]

**Pull request merged**
